import { Equipment, MuscleGroup, MovementType } from '@prisma/client';

export const EXERCISE_IMAGE_URLS: Record<string, string> = {
  'Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg',
  'Incline Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg',
  'Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/0.jpg',
  'Cable Crossover': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg',
  'Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg',
  'Machine Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg',
  'Svend Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Svend_Press/0.jpg',
  'Floor Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Press/0.jpg',
  'Push Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clock_Push-Up/0.jpg',
  'Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Axle_Deadlift/0.jpg',
  'Barbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg',
  'Dumbbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg',
  'Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg',
  'Lat Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg',
  'Cable Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elevated_Cable_Rows/0.jpg',
  'Face Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg',
  'T-Bar Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg',
  'Deficit Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Deficit_Deadlift/0.jpg',
  'Rack Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rack_Pull_with_Bands/0.jpg',
  'High Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Row/0.jpg',
  'Straight Arm Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight_Arm_Pulldown/0.jpg',
  'Wide Grip Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Pulldown/0.jpg',
  'Chin-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg',
  'Superman': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Superman/0.jpg',
  'Back Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Back_Extensions/0.jpg',
  'Front Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg',
  'Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg',
  'Leg Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg',
  'Leg Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Curls/0.jpg',
  'Hip Thrust': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg',
  'Romanian Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg',
  'Lunges': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg',
  'Incline Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Leg_Press/0.jpg',
  'Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg',
  'Hack Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg',
  'Goblet Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg',
  'Box Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Squat/0.jpg',
  'Sissy Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sissy_Squat/0.jpg',
  'Leg Press Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press_Calf_Raise/0.jpg',
  'Walking Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Lunges/0.jpg',
  'Reverse Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Lunges/0.jpg',
  'Pistol Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pistol_Squat/0.jpg',
  'Jefferson Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jefferson_Squats/0.jpg',
  'Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lateral_Raise/0.jpg',
  'Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Raise/0.jpg',
  'Arnold Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Rear Delt Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rear_Delt_Fly/0.jpg',
  'Cable Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg',
  'Cable Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Front_Raise/0.jpg',
  'Machine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Lateral_Raise/0.jpg',
  'Push Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Press/0.jpg',
  'Z Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Z_Press/0.jpg',
  'Bradford Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bradford_Press/0.jpg',
  'Y Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Y_Raise/0.jpg',
  'W Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/W_Raise/0.jpg',
  'Around The World': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Around_The_Worlds/0.jpg',
  'Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Row/0.jpg',
  'Cable Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Upright_Row/0.jpg',
  'Landmine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_Lateral_Raise/0.jpg',
  'Trap Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trap_Raise/0.jpg',
  'Barbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg',
  'EZ Bar Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg',
  'Alternating Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Dumbbell_Curl/0.jpg',
  'Hammer Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curl/0.jpg',
  'Concentration Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curl/0.jpg',
  'Cable Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg',
  'Incline Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg',
  'Preacher Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg',
  'Spider Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg',
  'Drag Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Drag_Curl/0.jpg',
  'Waiter Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Waiter_Curl/0.jpg',
  'Cross Body Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross_Body_Curl/0.jpg',
  'French Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/French_Press/0.jpg',
  'Triceps Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg',
  'Close Grip Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Bench_Press/0.jpg',
  'Triceps Dips': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Dips/0.jpg',
  'Triceps Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Kickback/0.jpg',
  'Overhead Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Triceps_Extension/0.jpg',
  'JM Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/JM_Press/0.jpg',
  'Cable Overhead Triceps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Overhead_Triceps/0.jpg',
  'Reverse Grip Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Pushdown/0.jpg',
  'Lying Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Extension/0.jpg',
  'Single Arm Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Triceps_Extension/0.jpg',
  'Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg',
  'Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch/0.jpg',
  'Cable Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg',
  'Ab Wheel Rollout': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Wheel_Rollout/0.jpg',
  'Hanging Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg',
  'Russian Twist': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg',
  'Dead Bug': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg',
  'Bird Dog': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bird_Dog/0.jpg',
  'Side Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/0.jpg',
  'V-Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Up/0.jpg',
  'Toe to Bar': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Toe_to_Bar/0.jpg',
  'Windshield Wiper': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Windshield_Wiper/0.jpg',
  'L-Sit': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/L-Sit/0.jpg',
  'Dragon Flag': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dragon_Flag/0.jpg',
  'Cable Woodchop': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Woodchop/0.jpg',
  'Pallof Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg',
  'Mountain Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climber/0.jpg',
  'Hollow Body Hold': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hollow_Body_Hold/0.jpg',
  'Bicycle Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycle_Crunch/0.jpg',
  'Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Raise/0.jpg',
  'Glute Bridge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Bridge/0.jpg',
  'Cable Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Kickback/0.jpg',
  'Bulgarian Split Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bulgarian_Split_Squat/0.jpg',
  'Step Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step-Up/0.jpg',
  'Sumo Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Squat/0.jpg',
  'Seated Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg',
  'Standing Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raise/0.jpg',
  'Donkey Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raise/0.jpg',
  'Single Leg Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Calf_Raise/0.jpg',
  'Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curl/0.jpg',
  'Reverse Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Curl/0.jpg',
  'Reverse Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curl/0.jpg',
  'Farmer Carry': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmer_Carry/0.jpg',
  'Plate Pinch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plate_Pinch/0.jpg',
  'Towel Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Towel_Pull-Up/0.jpg',
  'Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running/0.jpg',
  'Walking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking/0.jpg',
  'Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cycling/0.jpg',
  'Swimming': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming/0.jpg',
  'Rowing Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Machine/0.jpg',
  'Elliptical': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical/0.jpg',
  'Stair Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stair_Climber/0.jpg',
  'Jump Rope': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jump_Rope/0.jpg',
  'Sprint': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sprint/0.jpg',
  'Hiking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hiking/0.jpg',
  'Treadmill Run': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Run/0.jpg',
  'Treadmill Walk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Walk/0.jpg',
  'Stationary Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stationary_Bike/0.jpg',
  'Spin Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spin_Bike/0.jpg',
  'Indoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Indoor_Cycling/0.jpg',
  'Outdoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Outdoor_Cycling/0.jpg',
  'Trail Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trail_Running/0.jpg',
  'HIIT': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/HIIT/0.jpg',
  'Tabata': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tabata/0.jpg',
  'Circuit Training': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Circuit_Training/0.jpg',
  'Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Aerobics/0.jpg',
  'Dance': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dance/0.jpg',
  'Yoga': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Yoga/0.jpg',
  'Pilates': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pilates/0.jpg',
  'Stretching': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stretching/0.jpg',
  'Mobility': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mobility/0.jpg',
  'Foam Rolling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Foam_Rolling/0.jpg',
  'Swimming Laps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming_Laps/0.jpg',
  'Open Water Swim': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Open_Water_Swim/0.jpg',
  'Water Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Water_Aerobics/0.jpg',
  'Clean and Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/0.jpg',
  'Thruster': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thruster/0.jpg',
  'Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swing/0.jpg',
  'Burpee': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Burpee/0.jpg',
  'Turkish Get Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Turkish_Get_Up/0.jpg',
  'Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/0.jpg',
  'Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean/0.jpg',
  'Jerk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jerk/0.jpg',
  'Muscle Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Muscle_Up/0.jpg',
  'Box Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Jump/0.jpg',
  'Broad Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Broad_Jump/0.jpg',
  'Medicine Ball Slam': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Medicine_Ball_Slam/0.jpg',
  'Battle Ropes': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battle_Ropes/0.jpg',
  'Sled Push': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Push/0.jpg',
  'Sled Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Pull/0.jpg',
  'Wall Ball': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wall_Ball/0.jpg',
  'Kettlebell Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Clean/0.jpg',
  'Kettlebell Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Snatch/0.jpg',
  'Kettlebell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Press/0.jpg',
  'Single Arm Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Swing/0.jpg',
  'Goblet Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Clean/0.jpg',
  'Double Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Swing/0.jpg',
  'Kettlebell Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Squat/0.jpg',
  'Overhead Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Squat/0.jpg',
  'Incline Chest-Supported Dumbbell Row': 'https://wger.de/media/exercise-images/1283/e7262f70-7512-408a-8d00-4c499ef632fc.jpg',
  'Overhead Barbell Press': 'https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png',
  'Barbell Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg',
  'Dumbbell Pullover': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Pullover/0.jpg',
  'Good Morning': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg',
  'Hip Abduction Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hip_Abduction_Machine/0.jpg',
  'Hip Adduction Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hip_Adduction_Machine/0.jpg',
  'Landmine Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_Press/0.jpg',
  'Side Bend': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Bend/0.jpg',
  'Wrist Roller': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Roller/0.jpg',
  'Clamshell': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clamshell/0.jpg',
  'Side Lying Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lying_Leg_Raise/0.jpg',
  'Cat Camel': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Camel/0.jpg',
  'Jefferson Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jefferson_Curl/0.jpg',
  'Bear Crawl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bear_Crawl/0.jpg',
};

export const exercises = [
  // CHEST
  { name: 'Barbell Bench Press', nameEs: 'Press de banca plano con barra', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bench Press'] },
  { name: 'Incline Barbell Bench Press', nameEs: 'Press de banca inclinado con barra', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Incline Bench Press'] },
  { name: 'Decline Barbell Bench Press', nameEs: 'Press de banca declinado con barra', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bench Press'] },
  { name: 'Flat Dumbbell Press', nameEs: 'Press de banca plano con mancuernas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Incline Dumbbell Press', nameEs: 'Press de banca inclinado con mancuernas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Press'] },
  { name: 'Decline Dumbbell Press', nameEs: 'Press de banca declinado con mancuernas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Flat Dumbbell Fly', nameEs: 'Aperturas planas con mancuernas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Fly'] },
  { name: 'Incline Dumbbell Fly', nameEs: 'Aperturas inclinadas con mancuernas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Fly'] },
  { name: 'Dumbbell Pullover', nameEs: 'Pull-over con mancuerna', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Pullover'] },
  { name: 'High Cable Crossover', nameEs: 'Cruce de poleas altas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Low Cable Crossover', nameEs: 'Cruce de poleas bajas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Middle Cable Crossover', nameEs: 'Cruce de poleas a la altura media', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Machine Chest Press', nameEs: 'Press de pecho en máquina', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Pec Deck Fly', nameEs: 'Aperturas en máquina', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Push Up', nameEs: 'Flexiones de brazos', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Decline Push Up', nameEs: 'Flexiones declinadas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Incline Push Up', nameEs: 'Flexiones inclinadas', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Close Grip Push Up', nameEs: 'Flexiones de brazos con agarre cerrado', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Chest Dips', nameEs: 'Fondos en paralelas para pecho', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },

  // BACK
  { name: 'Pull Up', nameEs: 'Dominadas estrictas prono', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Chin Up', nameEs: 'Dominadas supino', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Chin-up'] },
  { name: 'Neutral Grip Pull Up', nameEs: 'Dominadas agarre neutro', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Lat Pulldown', nameEs: 'Jalón al pecho en polea alta', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Close Grip Lat Pulldown', nameEs: 'Jalón al pecho agarre cerrado', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Reverse Grip Lat Pulldown', nameEs: 'Jalón al pecho invertido', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Behind Neck Lat Pulldown', nameEs: 'Jalón tras nuca', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Straight Arm Pulldown', nameEs: 'Pull-over en polea alta', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Straight Arm Pulldown'] },
  { name: 'Bent Over Barbell Row', nameEs: 'Remo con barra libre', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Dumbbell Row', nameEs: 'Remo con mancuerna a una mano', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Row'] },
  { name: 'T-Bar Row', nameEs: 'Remo con barra en T', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['T-Bar Row'] },
  { name: 'Seated Cable Row', nameEs: 'Remo en polea baja', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Cable Row'] },
  { name: 'Hammer Strength Row', nameEs: 'Remo en máquina', muscleGroup: MuscleGroup.BACK, equipment: Equipment.MACHINE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['High Row'] },
  { name: 'Inverted Row', nameEs: 'Remo invertido', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Meadows Row', nameEs: 'Remo Meadows', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Seal Row', nameEs: 'Remo apoyado en banco inclinado', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Deadlift', nameEs: 'Peso muerto convencional', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Barbell Shrug', nameEs: 'Encogimientos de hombros con barra', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Dumbbell Shrug', nameEs: 'Encogimientos con mancuernas', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Calf Machine Shrug', nameEs: 'Encogimientos en máquina', muscleGroup: MuscleGroup.BACK, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Back Extension', nameEs: 'Hiperextensiones banco romano', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Back Extension'] },
  { name: 'Good Morning', nameEs: 'Buenos días con barra', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Good Morning'] },
  { name: 'Farmer Walk', nameEs: 'Paseo del granjero', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Farmer Carry'] },
  { name: 'Face Pull', nameEs: 'Jalones faciales', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Face Pull'] },

  // LEGS
  { name: 'Back Squat', nameEs: 'Sentadilla libre trasera con barra', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Barbell Squat'] },
  { name: 'Front Squat', nameEs: 'Sentadilla frontal con barra', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Front Squat'] },
  { name: 'Leg Press', nameEs: 'Prensa de piernas a 45°', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Leg Press'] },
  { name: 'Hack Squat', nameEs: 'Hack Squat máquina', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Hack Squat'] },
  { name: 'Bulgarian Split Squat', nameEs: 'Sentadilla búlgara', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Bulgarian Split Squat'] },
  { name: 'Walking Lunge', nameEs: 'Zancadas caminando', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Walking Lunge'] },
  { name: 'Reverse Lunge', nameEs: 'Zancadas estáticas hacia atrás', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Reverse Lunge'] },
  { name: 'Goblet Squat', nameEs: 'Sentadilla Goblet', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Goblet Squat'] },
  { name: 'Smith Machine Squat', nameEs: 'Sentadilla en multipower', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Box Squat'] },
  { name: 'Sumo Squat', nameEs: 'Sentadilla sumo con mancuerna', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Sumo Squat'] },
  { name: 'Pistol Squat', nameEs: 'Sentadilla pistola', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Pistol Squat'] },
  { name: 'Leg Extension', nameEs: 'Extensión de cuádriceps en máquina', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Extension'] },
  { name: 'Lying Leg Curl', nameEs: 'Curl de piernas acostado', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Seated Leg Curl', nameEs: 'Curl de piernas sentado', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Standing Leg Curl', nameEs: 'Curl de piernas de pie', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Romanian Deadlift', nameEs: 'Peso muerto rumano con barra', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Romanian Deadlift'] },
  { name: 'Dumbbell Romanian Deadlift', nameEs: 'Peso muerto rumano con mancuernas', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Romanian Deadlift'] },
  { name: 'Stiff Leg Deadlift', nameEs: 'Peso muerto piernas rígidas', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Barbell Hip Thrust', nameEs: 'Hip Thrust con barra', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Hip Thrust'] },
  { name: 'Glute Bridge', nameEs: 'Puente de glúteos', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Glute Bridge'] },
  { name: 'Hip Abduction Machine', nameEs: 'Máquina de abductores', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hip Abduction Machine'] },
  { name: 'Hip Adduction Machine', nameEs: 'Máquina de aductores', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hip Adduction Machine'] },
  { name: 'Cable Glute Kickback', nameEs: 'Patada de glúteo en polea', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Kickback'] },
  { name: 'Step Up', nameEs: 'Subidas al cajón', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Step Up'] },
  { name: 'Nordic Curl', nameEs: 'Curl nórdico', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },

  // SHOULDERS
  { name: 'Standing Barbell Overhead Press', nameEs: 'Press militar de pie con barra', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Overhead Barbell Press'] },
  { name: 'Seated Dumbbell Overhead Press', nameEs: 'Press de hombros sentado con mancuernas', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Arnold Press', nameEs: 'Press Arnold', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Arnold Press'] },
  { name: 'Machine Shoulder Press', nameEs: 'Press de hombros en máquina', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Smith Machine Shoulder Press', nameEs: 'Press de hombros en multipower', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Overhead Barbell Press'] },
  { name: 'Landmine Press', nameEs: 'Press unilateral barra esquina', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Landmine Press'] },
  { name: 'Dumbbell Lateral Raise', nameEs: 'Elevaciones laterales con mancuernas', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Lateral Raise'] },
  { name: 'Cable Lateral Raise', nameEs: 'Elevaciones laterales en polea baja', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Lateral Raise'] },
  { name: 'Dumbbell Front Raise', nameEs: 'Elevaciones frontales con mancuernas', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Plate Front Raise', nameEs: 'Elevaciones frontales con disco', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Barbell Front Raise', nameEs: 'Elevaciones frontales con barra', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Bent Over Dumbbell Rear Delt Fly', nameEs: 'Pájaros con mancuernas', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Rear Delt Fly'] },
  { name: 'Reverse Pec Deck Fly', nameEs: 'Pájaros en máquina Contractor', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Incline Lateral Raise', nameEs: 'Elevaciones laterales acostado en banco', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Lateral Raise'] },
  { name: 'Barbell Upright Row', nameEs: 'Remo al mentón con barra', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Upright Row'] },
  { name: 'Cable Upright Row', nameEs: 'Remo al mentón en polea', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Cable Upright Row'] },

  // BICEPS
  { name: 'Straight Bar Curl', nameEs: 'Curl de bíceps con barra recta', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Barbell Curl'] },
  { name: 'EZ Bar Curl', nameEs: 'Curl de bíceps con barra Z', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['EZ Bar Curl'] },
  { name: 'Alternating Dumbbell Curl', nameEs: 'Curl de bíceps con mancuernas alterno', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Alternating Dumbbell Curl'] },
  { name: 'Hammer Curl', nameEs: 'Curl martillo', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hammer Curl'] },
  { name: 'Concentration Curl', nameEs: 'Curl concentrado', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Concentration Curl'] },
  { name: 'Preacher Curl Bar', nameEs: 'Curl banco Scott con barra Z', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Preacher Curl'] },
  { name: 'Preacher Curl Dumbbell', nameEs: 'Curl banco Scott con mancuerna', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Preacher Curl'] },
  { name: 'Incline Dumbbell Curl', nameEs: 'Curl inclinado con mancuernas', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Curl'] },
  { name: 'Cable Bar Curl', nameEs: 'Curl en polea baja con barra', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },
  { name: 'Cable Rope Curl', nameEs: 'Curl en polea baja con cuerda', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },
  { name: 'Spider Curl', nameEs: 'Curl araña', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Spider Curl'] },
  { name: 'Reverse Barbell Curl', nameEs: 'Curl inverso con barra', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Curl'] },
  { name: 'Zottman Curl', nameEs: 'Curl Zottman', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hammer Curl'] },
  { name: '21 Curl', nameEs: 'Curl 21', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Barbell Curl'] },
  { name: 'Cable Cross Curl', nameEs: 'Curl en poleas altas dobles', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },

  // TRICEPS
  { name: 'Close Grip Bench Press', nameEs: 'Press de banca agarre cerrado', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Close Grip Bench Press'] },
  { name: 'Triceps Dips', nameEs: 'Fondos en paralelas para tríceps', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },
  { name: 'Bench Dips', nameEs: 'Fondos entre dos bancos', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },
  { name: 'Triceps Pushdown Bar', nameEs: 'Extensión de tríceps en polea con barra recta', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Pushdown'] },
  { name: 'Triceps Pushdown Rope', nameEs: 'Extensión de tríceps en polea con cuerda', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Pushdown'] },
  { name: 'Reverse Grip Pushdown', nameEs: 'Extensión en polea agarre invertido', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Grip Pushdown'] },
  { name: 'EZ Bar Skull Crusher', nameEs: 'Press francés con barra Z', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['French Press'] },
  { name: 'Dumbbell Skull Crusher', nameEs: 'Press francés con mancuernas', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['French Press'] },
  { name: 'Two Hand Dumbbell Triceps Extension', nameEs: 'Extensión de tríceps tras nuca con mancuerna a dos manos', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'Single Arm Dumbbell Triceps Extension', nameEs: 'Extensión de tríceps tras nuca unilateral', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'Cable Overhead Triceps Extension', nameEs: 'Extensión de tríceps tras nuca en polea baja', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Overhead Triceps'] },
  { name: 'Triceps Kickback', nameEs: 'Patada de tríceps con mancuerna', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Kickback'] },
  { name: 'Cable Triceps Kickback', nameEs: 'Patada de tríceps en polea', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Kickback'] },
  { name: 'Diamond Push Up', nameEs: 'Flexiones diamante', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Close Grip Floor Press', nameEs: 'Press de suelo agarre cerrado', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Floor Press'] },

  // CORE
  { name: 'Crunch', nameEs: 'Crunches clásicos', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Decline Crunch', nameEs: 'Crunches en banco declinado', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Cable Crunch', nameEs: 'Crunches en polea alta', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crunch'] },
  { name: 'Hanging Leg Raise', nameEs: 'Elevaciones de piernas suspendido en barra', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hanging Leg Raise'] },
  { name: 'Captain Chair Leg Raise', nameEs: 'Elevaciones de rodillas en silla capitán', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Raise'] },
  { name: 'Lying Leg Raise', nameEs: 'Elevaciones de piernas tumbado', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Raise'] },
  { name: 'Reverse Crunch', nameEs: 'Crunch invertido', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'V Up', nameEs: 'V-ups', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['V-Up'] },
  { name: 'Ab Wheel Rollout', nameEs: 'Rueda abdominal', muscleGroup: MuscleGroup.CORE, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Ab Wheel Rollout'] },
  { name: 'Sit Up', nameEs: 'Abdominales completos', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Plank', nameEs: 'Plancha frontal', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Side Plank', nameEs: 'Plancha lateral', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Side Plank'] },
  { name: 'Russian Twist', nameEs: 'Giros rusos', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Russian Twist'] },
  { name: 'Pallof Press', nameEs: 'Press Pallof', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Pallof Press'] },
  { name: 'Side Bend', nameEs: 'Flexión lateral de tronco con mancuerna', muscleGroup: MuscleGroup.CORE, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Side Bend'] },
  { name: 'Cable Woodchop', nameEs: 'Leñador en polea', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Woodchop'] },
  { name: 'Mountain Climber', nameEs: 'Escaladores', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Mountain Climber'] },
  { name: 'Bicycle Crunch', nameEs: 'Abdominales bicicleta', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Bicycle Crunch'] },
  { name: 'Heel Touch', nameEs: 'Toques de tobillo', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Dead Bug', nameEs: 'Bicho muerto', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Dead Bug'] },
  { name: 'Bird Dog', nameEs: 'Pájaro perro', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Bird Dog'] },
  { name: 'L Sit', nameEs: 'L-Sit', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['L-Sit'] },

  // CALVES
  { name: 'Standing Calf Raise', nameEs: 'Elevación de talones de pie en máquina', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Standing Calf Raise'] },
  { name: 'Seated Calf Raise', nameEs: 'Elevación de talones sentado en máquina', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Seated Calf Raise'] },
  { name: 'Leg Press Calf Raise', nameEs: 'Elevación de talones en prensa de piernas', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Press Calf Raise'] },
  { name: 'Donkey Calf Raise', nameEs: 'Elevación de talones burro', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Donkey Calf Raise'] },
  { name: 'Single Leg Calf Raise', nameEs: 'Elevación de talones unilateral con mancuerna', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Single Leg Calf Raise'] },

  // FOREARMS
  { name: 'Wrist Curl', nameEs: 'Curl de antebrazo con barra en pronación', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Wrist Curl'] },
  { name: 'Reverse Wrist Curl', nameEs: 'Curl de antebrazo con barra en supinación', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Wrist Curl'] },
  { name: 'Wrist Roller', nameEs: 'Rodillo de muñeca', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Wrist Roller'] },
  { name: 'Plate Pinch', nameEs: 'Sujeción de discos con dedos', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Plate Pinch'] },

  // FULL_BODY
  { name: 'Clean and Jerk', nameEs: 'Cargada y envión', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Clean and Press'] },
  { name: 'Snatch', nameEs: 'Arranque', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Snatch'] },
  { name: 'Power Clean', nameEs: 'Cargada de potencia', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Clean'] },
  { name: 'Hang Clean', nameEs: 'Cargada desde colgado', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Clean'] },
  { name: 'Push Press', nameEs: 'Press de empuje', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Press'] },
  { name: 'Thruster', nameEs: 'Sentadilla con press', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Thruster'] },
  { name: 'Kettlebell Swing', nameEs: 'Balanceo con kettlebell', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.KETTLEBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Kettlebell Swing'] },
  { name: 'Wall Ball', nameEs: 'Lanzamiento a pared', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Wall Ball'] },
  { name: 'Burpee', nameEs: 'Flexión con salto', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Burpee'] },
  { name: 'Box Jump', nameEs: 'Salto al cajón', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Box Jump'] },
  { name: 'Jump Rope', nameEs: 'Saltar la soga', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Jump Rope'] },
  { name: 'Sled Push', nameEs: 'Empuje de trineo', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Sled Push'] },
  { name: 'Dumbbell Snatch', nameEs: 'Arranque con mancuerna', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Snatch'] },

  // EXTRA VARIATIONS
  { name: 'Floor Press', nameEs: 'Press de suelo con barra', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Floor Press'] },
  { name: 'Trap Bar Deadlift', nameEs: 'Peso muerto con barra hexagonal', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Sumo Deadlift', nameEs: 'Peso muerto sumo', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Deficit Deadlift', nameEs: 'Peso muerto en déficit', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deficit Deadlift'] },
  { name: 'Pendlay Row', nameEs: 'Remo Pendlay', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Commando Pull Up', nameEs: 'Dominadas comando', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Commando Push Up', nameEs: 'Flexiones comando', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Clap Push Up', nameEs: 'Flexiones con palmada', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Handstand Push Up', nameEs: 'Flexiones de pino', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Y Raise', nameEs: 'Elevaciones en Y', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Y Raise'] },
  { name: 'Scapular Push Up', nameEs: 'Flexión escapular', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Clamshell', nameEs: 'Clamshell con banda', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.RESISTANCE_BAND, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Clamshell'] },
  { name: 'Side Lying Leg Raise', nameEs: 'Elevación lateral de piernas', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Side Lying Leg Raise'] },
  { name: 'Cross Body Mountain Climber', nameEs: 'Escalador cruzado', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Mountain Climber'] },
  { name: 'Plank Shoulder Tap', nameEs: 'Plancha con toques de hombro', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Spiderman Plank', nameEs: 'Plancha Spiderman', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Cat Camel', nameEs: 'Gato camello', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cat Camel'] },
  { name: 'High Cable Rear Delt Row', nameEs: 'Remo alto para deltoides posterior en polea', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Face Pull'] },
  { name: 'Unilateral Machine Chest Press', nameEs: 'Press de pecho unilateral en máquina', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Forward Lunge', nameEs: 'Zancadas estáticas hacia adelante', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Lunges'] },
  { name: 'Smith Machine Drag Curl', nameEs: 'Curl de bíceps en multipower arrastrado', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Drag Curl'] },
  { name: 'Incline Bench Triceps Extension', nameEs: 'Extensión de tríceps tumbado en banco inclinado', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'High Pull', nameEs: 'Tirón alto con barra', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Upright Row'] },
  { name: 'Bear Crawl', nameEs: 'Paseo del oso', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Bear Crawl'] },
];

export async function seedExercises(prismaClient: any) {
  console.log('Seeding exercises...');

  const allExercises = await prismaClient.exercise.findMany({
    where: { isGlobal: true },
    select: { id: true, name: true },
    orderBy: { id: 'asc' },
  });

  const nameMap = new Map<string, string>();
  let totalRemoved = 0;

  for (const ex of allExercises) {
    if (nameMap.has(ex.name)) {
      const keepId = nameMap.get(ex.name)!;
      const updatedSets = await prismaClient.set.updateMany({
        where: { exerciseId: ex.id },
        data: { exerciseId: keepId },
      });
      if (updatedSets.count > 0) {
        console.log(`  Reassigned ${updatedSets.count} sets from "${ex.name}" duplicate to original`);
      }
      await prismaClient.exercise.delete({ where: { id: ex.id } });
      totalRemoved++;
      console.log(`  Removed duplicate: "${ex.name}" (id: ${ex.id})`);
    } else {
      nameMap.set(ex.name, ex.id);
    }
  }

  if (totalRemoved > 0) {
    console.log(`✅ Removed ${totalRemoved} duplicate exercises`);
  } else {
    console.log('✅ No duplicate exercises found');
  }

  const existingNames = new Set(allExercises.map(e => e.name));
  const newExercises = exercises.filter(e => !existingNames.has(e.name));

  if (newExercises.length > 0) {
    await prismaClient.exercise.createMany({
      data: newExercises.map(e => ({
        ...e,
        isGlobal: true,
        secondaryMuscles: [],
        userId: null,
      })),
      skipDuplicates: true,
    });
    console.log(`✅ Seeded ${newExercises.length} new exercises (${existingNames.size} already existed)`);
  } else {
    console.log(`✅ All ${exercises.length} exercises already exist, no new exercises seeded`);
  }

  console.log('Updating exercise images...');
  let updatedImages = 0;
  for (const ex of exercises) {
    if (ex.imageUrl) {
      const result = await prismaClient.exercise.updateMany({
        where: { name: ex.name, isGlobal: true },
        data: { imageUrl: ex.imageUrl },
      });
      if (result.count > 0) {
        updatedImages += result.count;
      }
    }
  }
  console.log(`✅ Updated ${updatedImages} exercise images`);
}