import { Equipment, MuscleGroup, MovementType } from '@prisma/client';

export const EXERCISE_IMAGE_URLS: Record<string, string> = {
  'Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg',
  'Incline Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg',
  'Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/0.jpg',
  'Cable Crossover': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg',
  'Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg',
  'Machine Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg',
  'Svend Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Svend_Press/0.jpg',
  'Floor Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Press/0.jpg',
  'Push Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clock_Push-Up/0.jpg',
  'Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Axle_Deadlift/0.jpg',
  'Barbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg',
  'Dumbbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg',
  'Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg',
  'Lat Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg',
  'Cable Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elevated_Cable_Rows/0.jpg',
  'Face Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg',
  'T-Bar Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg',
  'Deficit Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Deficit_Deadlift/0.jpg',
  'Rack Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rack_Pull_with_Bands/0.jpg',
  'High Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Row/0.jpg',
  'Straight Arm Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight_Arm_Pulldown/0.jpg',
  'Wide Grip Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Pulldown/0.jpg',
  'Chin-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg',
  'Superman': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Superman/0.jpg',
  'Back Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Back_Extensions/0.jpg',
  'Front Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg',
  'Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg',
  'Leg Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg',
  'Leg Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Curls/0.jpg',
  'Hip Thrust': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg',
  'Romanian Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg',
  'Lunges': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg',
  'Incline Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Leg_Press/0.jpg',
  'Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg',
  'Hack Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg',
  'Goblet Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg',
  'Box Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Squat/0.jpg',
  'Sissy Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sissy_Squat/0.jpg',
  'Leg Press Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press_Calf_Raise/0.jpg',
  'Walking Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Lunges/0.jpg',
  'Reverse Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Lunges/0.jpg',
  'Pistol Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pistol_Squat/0.jpg',
  'Jefferson Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jefferson_Squats/0.jpg',
  'Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lateral_Raise/0.jpg',
  'Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Raise/0.jpg',
  'Arnold Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Rear Delt Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rear_Delt_Fly/0.jpg',
  'Cable Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg',
  'Cable Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Front_Raise/0.jpg',
  'Machine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Lateral_Raise/0.jpg',
  'Push Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Press/0.jpg',
  'Z Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Z_Press/0.jpg',
  'Bradford Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bradford_Press/0.jpg',
  'Y Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Y_Raise/0.jpg',
  'W Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/W_Raise/0.jpg',
  'Around The World': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Around_The_Worlds/0.jpg',
  'Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Row/0.jpg',
  'Cable Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Upright_Row/0.jpg',
  'Landmine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_Lateral_Raise/0.jpg',
  'Trap Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trap_Raise/0.jpg',
  'Barbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg',
  'EZ Bar Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg',
  'Alternating Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Dumbbell_Curl/0.jpg',
  'Hammer Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curl/0.jpg',
  'Concentration Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curl/0.jpg',
  'Cable Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg',
  'Incline Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg',
  'Preacher Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg',
  'Spider Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg',
  'Drag Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Drag_Curl/0.jpg',
  'Waiter Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Waiter_Curl/0.jpg',
  'Cross Body Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross_Body_Curl/0.jpg',
  'French Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/French_Press/0.jpg',
  'Triceps Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg',
  'Close Grip Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Bench_Press/0.jpg',
  'Triceps Dips': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Dips/0.jpg',
  'Triceps Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Kickback/0.jpg',
  'Overhead Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Triceps_Extension/0.jpg',
  'JM Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/JM_Press/0.jpg',
  'Cable Overhead Triceps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Overhead_Triceps/0.jpg',
  'Reverse Grip Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Pushdown/0.jpg',
  'Lying Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Extension/0.jpg',
  'Single Arm Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Triceps_Extension/0.jpg',
  'Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg',
  'Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch/0.jpg',
  'Cable Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg',
  'Ab Wheel Rollout': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Wheel_Rollout/0.jpg',
  'Hanging Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg',
  'Russian Twist': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg',
  'Dead Bug': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg',
  'Bird Dog': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bird_Dog/0.jpg',
  'Side Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/0.jpg',
  'V-Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Up/0.jpg',
  'Toe to Bar': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Toe_to_Bar/0.jpg',
  'Windshield Wiper': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Windshield_Wiper/0.jpg',
  'L-Sit': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/L-Sit/0.jpg',
  'Dragon Flag': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dragon_Flag/0.jpg',
  'Cable Woodchop': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Woodchop/0.jpg',
  'Pallof Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg',
  'Mountain Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climber/0.jpg',
  'Hollow Body Hold': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hollow_Body_Hold/0.jpg',
  'Bicycle Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycle_Crunch/0.jpg',
  'Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Raise/0.jpg',
  'Glute Bridge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Bridge/0.jpg',
  'Cable Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Kickback/0.jpg',
  'Bulgarian Split Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bulgarian_Split_Squat/0.jpg',
  'Step Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step-Up/0.jpg',
  'Sumo Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Squat/0.jpg',
  'Seated Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg',
  'Standing Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raise/0.jpg',
  'Donkey Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raise/0.jpg',
  'Single Leg Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Calf_Raise/0.jpg',
  'Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curl/0.jpg',
  'Reverse Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Curl/0.jpg',
  'Reverse Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curl/0.jpg',
  'Farmer Carry': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmer_Carry/0.jpg',
  'Plate Pinch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plate_Pinch/0.jpg',
  'Towel Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Towel_Pull-Up/0.jpg',
  'Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running/0.jpg',
  'Walking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking/0.jpg',
  'Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cycling/0.jpg',
  'Swimming': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming/0.jpg',
  'Rowing Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Machine/0.jpg',
  'Elliptical': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical/0.jpg',
  'Stair Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stair_Climber/0.jpg',
  'Jump Rope': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jump_Rope/0.jpg',
  'Sprint': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sprint/0.jpg',
  'Hiking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hiking/0.jpg',
  'Treadmill Run': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Run/0.jpg',
  'Treadmill Walk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Walk/0.jpg',
  'Stationary Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stationary_Bike/0.jpg',
  'Spin Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spin_Bike/0.jpg',
  'Indoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Indoor_Cycling/0.jpg',
  'Outdoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Outdoor_Cycling/0.jpg',
  'Trail Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trail_Running/0.jpg',
  'HIIT': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/HIIT/0.jpg',
  'Tabata': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tabata/0.jpg',
  'Circuit Training': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Circuit_Training/0.jpg',
  'Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Aerobics/0.jpg',
  'Dance': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dance/0.jpg',
  'Yoga': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Yoga/0.jpg',
  'Pilates': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pilates/0.jpg',
  'Stretching': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stretching/0.jpg',
  'Mobility': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mobility/0.jpg',
  'Foam Rolling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Foam_Rolling/0.jpg',
  'Swimming Laps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming_Laps/0.jpg',
  'Open Water Swim': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Open_Water_Swim/0.jpg',
  'Water Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Water_Aerobics/0.jpg',
  'Clean and Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/0.jpg',
  'Thruster': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thruster/0.jpg',
  'Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swing/0.jpg',
  'Burpee': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Burpee/0.jpg',
  'Turkish Get Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Turkish_Get_Up/0.jpg',
  'Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/0.jpg',
  'Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean/0.jpg',
  'Jerk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jerk/0.jpg',
  'Muscle Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Muscle_Up/0.jpg',
  'Box Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Jump/0.jpg',
  'Broad Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Broad_Jump/0.jpg',
  'Medicine Ball Slam': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Medicine_Ball_Slam/0.jpg',
  'Battle Ropes': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battle_Ropes/0.jpg',
  'Sled Push': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Push/0.jpg',
  'Sled Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Pull/0.jpg',
  'Wall Ball': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wall_Ball/0.jpg',
  'Kettlebell Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Clean/0.jpg',
  'Kettlebell Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Snatch/0.jpg',
  'Kettlebell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Press/0.jpg',
  'Single Arm Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Swing/0.jpg',
  'Goblet Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Clean/0.jpg',
  'Double Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Swing/0.jpg',
  'Kettlebell Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Squat/0.jpg',
  'Overhead Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Squat/0.jpg',
  'Incline Chest-Supported Dumbbell Row': 'https://wger.de/media/exercise-images/1283/e7262f70-7512-408a-8d00-4c499ef632fc.jpg',
  'Overhead Barbell Press': 'https://wger.de/media/exercise-images/1893/7dbad19e-0616-41fd-9d7d-3e21649c0eea.png',
  'Barbell Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg',
  'Dumbbell Pullover': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Pullover/0.jpg',
  'Good Morning': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg',
  'Hip Abduction Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hip_Abduction_Machine/0.jpg',
  'Hip Adduction Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hip_Adduction_Machine/0.jpg',
  'Landmine Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_Press/0.jpg',
  'Side Bend': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Bend/0.jpg',
  'Wrist Roller': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Roller/0.jpg',
  'Clamshell': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clamshell/0.jpg',
  'Side Lying Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lying_Leg_Raise/0.jpg',
  'Cat Camel': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cat_Camel/0.jpg',
  'Jefferson Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jefferson_Curl/0.jpg',
  'Bear Crawl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bear_Crawl/0.jpg',
};

export const exercises = [
  // CHEST
  { name: 'Press de banca plano con barra', nameEs: 'Barbell Bench Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bench Press'] },
  { name: 'Press de banca inclinado con barra', nameEs: 'Incline Barbell Bench Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Incline Bench Press'] },
  { name: 'Press de banca declinado con barra', nameEs: 'Decline Barbell Bench Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bench Press'] },
  { name: 'Press de banca plano con mancuernas', nameEs: 'Flat Dumbbell Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Press de banca inclinado con mancuernas', nameEs: 'Incline Dumbbell Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Press'] },
  { name: 'Press de banca declinado con mancuernas', nameEs: 'Decline Dumbbell Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Aperturas planas con mancuernas', nameEs: 'Flat Dumbbell Fly', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Fly'] },
  { name: 'Aperturas inclinadas con mancuernas', nameEs: 'Incline Dumbbell Fly', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Fly'] },
  { name: 'Press Svend', nameEs: 'Svend Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Svend Press'] },
  { name: 'Pull-over con mancuerna', nameEs: 'Dumbbell Pullover', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Pullover'] },
  { name: 'Cruce de poleas altas', nameEs: 'High Cable Crossover', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Cruce de poleas bajas', nameEs: 'Low Cable Crossover', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Cruce de poleas a la altura media', nameEs: 'Middle Cable Crossover', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crossover'] },
  { name: 'Press de pecho en máquina', nameEs: 'Machine Chest Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Aperturas en máquina', nameEs: 'Pec Deck Fly', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Flexiones de brazos', nameEs: 'Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Flexiones declinadas', nameEs: 'Decline Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Flexiones inclinadas', nameEs: 'Incline Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Flexiones de brazos con agarre cerrado', nameEs: 'Close Grip Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Fondos en paralelas para pecho', nameEs: 'Chest Dips', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },

  // BACK
  { name: 'Dominadas estrictas prono', nameEs: 'Pull Up', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Dominadas supino', nameEs: 'Chin Up', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Chin-up'] },
  { name: 'Dominadas agarre neutro', nameEs: 'Neutral Grip Pull Up', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Jalón al pecho en polea alta', nameEs: 'Lat Pulldown', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Jalón al pecho agarre cerrado', nameEs: 'Close Grip Lat Pulldown', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Jalón al pecho invertido', nameEs: 'Reverse Grip Lat Pulldown', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Jalón tras nuca', nameEs: 'Behind Neck Lat Pulldown', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Lat Pulldown'] },
  { name: 'Pull-over en polea alta', nameEs: 'Straight Arm Pulldown', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Straight Arm Pulldown'] },
  { name: 'Remo con barra libre', nameEs: 'Bent Over Barbell Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Remo con mancuerna a una mano', nameEs: 'Dumbbell Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Row'] },
  { name: 'Remo con barra en T', nameEs: 'T-Bar Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['T-Bar Row'] },
  { name: 'Remo en polea baja', nameEs: 'Seated Cable Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Cable Row'] },
  { name: 'Remo en máquina', nameEs: 'Hammer Strength Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.MACHINE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['High Row'] },
  { name: 'Remo invertido', nameEs: 'Inverted Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Remo Meadows', nameEs: 'Meadows Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Remo apoyado en banco inclinado', nameEs: 'Seal Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Peso muerto convencional', nameEs: 'Deadlift', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Encogimientos de hombros con barra', nameEs: 'Barbell Shrug', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Encogimientos con mancuernas', nameEs: 'Dumbbell Shrug', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Encogimientos en máquina', nameEs: 'Calf Machine Shrug', muscleGroup: MuscleGroup.BACK, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Trap Raise'] },
  { name: 'Hiperextensiones banco romano', nameEs: 'Back Extension', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Back Extension'] },
  { name: 'Buenos días con barra', nameEs: 'Good Morning', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Good Morning'] },
  { name: 'Paseo del granjero', nameEs: 'Farmer Walk', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Farmer Carry'] },
  { name: 'Jalones faciales', nameEs: 'Face Pull', muscleGroup: MuscleGroup.BACK, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Face Pull'] },

  // LEGS
  { name: 'Sentadilla libre trasera con barra', nameEs: 'Back Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Barbell Squat'] },
  { name: 'Sentadilla frontal con barra', nameEs: 'Front Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Front Squat'] },
  { name: 'Prensa de piernas a 45°', nameEs: 'Leg Press', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Leg Press'] },
  { name: 'Hack Squat máquina', nameEs: 'Hack Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Hack Squat'] },
  { name: 'Sentadilla búlgara', nameEs: 'Bulgarian Split Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Bulgarian Split Squat'] },
  { name: 'Zancadas caminando', nameEs: 'Walking Lunge', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Walking Lunge'] },
  { name: 'Zancadas estáticas hacia atrás', nameEs: 'Reverse Lunge', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Reverse Lunge'] },
  { name: 'Sentadilla Goblet', nameEs: 'Goblet Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Goblet Squat'] },
  { name: 'Sentadilla en multipower', nameEs: 'Smith Machine Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Box Squat'] },
  { name: 'Sentadilla sumo con mancuerna', nameEs: 'Sumo Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Sumo Squat'] },
  { name: 'Sentadilla pistola', nameEs: 'Pistol Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Pistol Squat'] },
  { name: 'Extensión de cuádriceps en máquina', nameEs: 'Leg Extension', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Extension'] },
  { name: 'Curl de piernas acostado', nameEs: 'Lying Leg Curl', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Curl de piernas sentado', nameEs: 'Seated Leg Curl', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Curl de piernas de pie', nameEs: 'Standing Leg Curl', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },
  { name: 'Peso muerto rumano con barra', nameEs: 'Romanian Deadlift', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Romanian Deadlift'] },
  { name: 'Peso muerto rumano con mancuernas', nameEs: 'Dumbbell Romanian Deadlift', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Romanian Deadlift'] },
  { name: 'Peso muerto piernas rígidas', nameEs: 'Stiff Leg Deadlift', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Hip Thrust con barra', nameEs: 'Barbell Hip Thrust', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Hip Thrust'] },
  { name: 'Puente de glúteos', nameEs: 'Glute Bridge', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Glute Bridge'] },
  { name: 'Máquina de abductores', nameEs: 'Hip Abduction Machine', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hip Abduction Machine'] },
  { name: 'Máquina de aductores', nameEs: 'Hip Adduction Machine', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hip Adduction Machine'] },
  { name: 'Patada de glúteo en polea', nameEs: 'Cable Glute Kickback', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Kickback'] },
  { name: 'Subidas al cajón', nameEs: 'Step Up', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Step Up'] },
  { name: 'Curl nórdico', nameEs: 'Nordic Curl', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Curl'] },

  // SHOULDERS
  { name: 'Press militar de pie con barra', nameEs: 'Standing Barbell Overhead Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Overhead Barbell Press'] },
  { name: 'Press de hombros sentado con mancuernas', nameEs: 'Seated Dumbbell Overhead Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Press Arnold', nameEs: 'Arnold Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Arnold Press'] },
  { name: 'Press de hombros en máquina', nameEs: 'Machine Shoulder Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Press'] },
  { name: 'Press de hombros en multipower', nameEs: 'Smith Machine Shoulder Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Overhead Barbell Press'] },
  { name: 'Press unilateral barra esquina', nameEs: 'Landmine Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Landmine Press'] },
  { name: 'Elevaciones laterales con mancuernas', nameEs: 'Dumbbell Lateral Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Lateral Raise'] },
  { name: 'Elevaciones laterales en polea baja', nameEs: 'Cable Lateral Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Lateral Raise'] },
  { name: 'Elevaciones frontales con mancuernas', nameEs: 'Dumbbell Front Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Elevaciones frontales con disco', nameEs: 'Plate Front Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Elevaciones frontales con barra', nameEs: 'Barbell Front Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Front Raise'] },
  { name: 'Pájaros con mancuernas', nameEs: 'Bent Over Dumbbell Rear Delt Fly', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Rear Delt Fly'] },
  { name: 'Pájaros en máquina Contractor', nameEs: 'Reverse Pec Deck Fly', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Elevaciones laterales acostado en banco', nameEs: 'Incline Lateral Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Lateral Raise'] },
  { name: 'Remo al mentón con barra', nameEs: 'Barbell Upright Row', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Upright Row'] },
  { name: 'Remo al mentón en polea', nameEs: 'Cable Upright Row', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Cable Upright Row'] },

  // BICEPS
  { name: 'Curl de bíceps con barra recta', nameEs: 'Straight Bar Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Barbell Curl'] },
  { name: 'Curl de bíceps con barra Z', nameEs: 'EZ Bar Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['EZ Bar Curl'] },
  { name: 'Curl de bíceps con mancuernas alterno', nameEs: 'Alternating Dumbbell Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Alternating Dumbbell Curl'] },
  { name: 'Curl martillo', nameEs: 'Hammer Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hammer Curl'] },
  { name: 'Curl concentrado', nameEs: 'Concentration Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Concentration Curl'] },
  { name: 'Curl banco Scott con barra Z', nameEs: 'Preacher Curl Bar', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Preacher Curl'] },
  { name: 'Curl banco Scott con mancuerna', nameEs: 'Preacher Curl Dumbbell', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Preacher Curl'] },
  { name: 'Curl inclinado con mancuernas', nameEs: 'Incline Dumbbell Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Incline Dumbbell Curl'] },
  { name: 'Curl en polea baja con barra', nameEs: 'Cable Bar Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },
  { name: 'Curl en polea baja con cuerda', nameEs: 'Cable Rope Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },
  { name: 'Curl araña', nameEs: 'Spider Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Spider Curl'] },
  { name: 'Curl inverso con barra', nameEs: 'Reverse Barbell Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Curl'] },
  { name: 'Curl Zottman', nameEs: 'Zottman Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hammer Curl'] },
  { name: 'Curl 21', nameEs: '21 Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Barbell Curl'] },
  { name: 'Curl en poleas altas dobles', nameEs: 'Cable Cross Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Curl'] },

  // TRICEPS
  { name: 'Press de banca agarre cerrado', nameEs: 'Close Grip Bench Press', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Close Grip Bench Press'] },
  { name: 'Fondos en paralelas para tríceps', nameEs: 'Triceps Dips', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },
  { name: 'Fondos entre dos bancos', nameEs: 'Bench Dips', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Triceps Dips'] },
  { name: 'Extensión de tríceps en polea con barra recta', nameEs: 'Triceps Pushdown Bar', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Pushdown'] },
  { name: 'Extensión de tríceps en polea con cuerda', nameEs: 'Triceps Pushdown Rope', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Pushdown'] },
  { name: 'Extensión en polea agarre invertido', nameEs: 'Reverse Grip Pushdown', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Grip Pushdown'] },
  { name: 'Press francés con barra Z', nameEs: 'EZ Bar Skull Crusher', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['French Press'] },
  { name: 'Press francés con mancuernas', nameEs: 'Dumbbell Skull Crusher', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['French Press'] },
  { name: 'Extensión de tríceps tras nuca con mancuerna a dos manos', nameEs: 'Two Hand Dumbbell Triceps Extension', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'Extensión de tríceps tras nuca unilateral', nameEs: 'Single Arm Dumbbell Triceps Extension', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'Extensión de tríceps tras nuca en polea baja', nameEs: 'Cable Overhead Triceps Extension', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Overhead Triceps'] },
  { name: 'Patada de tríceps con mancuerna', nameEs: 'Triceps Kickback', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Kickback'] },
  { name: 'Patada de tríceps en polea', nameEs: 'Cable Triceps Kickback', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Triceps Kickback'] },
  { name: 'Flexiones diamante', nameEs: 'Diamond Push Up', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Press de suelo agarre cerrado', nameEs: 'Close Grip Floor Press', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Floor Press'] },

  // CORE
  { name: 'Crunches clásicos', nameEs: 'Crunch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Crunches en banco declinado', nameEs: 'Decline Crunch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Crunches en polea alta', nameEs: 'Cable Crunch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Crunch'] },
  { name: 'Elevaciones de piernas suspendido en barra', nameEs: 'Hanging Leg Raise', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Hanging Leg Raise'] },
  { name: 'Elevaciones de rodillas en silla capitán', nameEs: 'Captain Chair Leg Raise', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Raise'] },
  { name: 'Elevaciones de piernas tumbado', nameEs: 'Lying Leg Raise', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Raise'] },
  { name: 'Crunch invertido', nameEs: 'Reverse Crunch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'V-ups', nameEs: 'V Up', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['V-Up'] },
  { name: 'Rueda abdominal', nameEs: 'Ab Wheel Rollout', muscleGroup: MuscleGroup.CORE, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Ab Wheel Rollout'] },
  { name: 'Abdominales completos', nameEs: 'Sit Up', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Plancha frontal', nameEs: 'Plank', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Plancha lateral', nameEs: 'Side Plank', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Side Plank'] },
  { name: 'Giros rusos', nameEs: 'Russian Twist', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Russian Twist'] },
  { name: 'Press Pallof', nameEs: 'Pallof Press', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Pallof Press'] },
  { name: 'Flexión lateral de tronco con mancuerna', nameEs: 'Side Bend', muscleGroup: MuscleGroup.CORE, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Side Bend'] },
  { name: 'Leñador en polea', nameEs: 'Cable Woodchop', muscleGroup: MuscleGroup.CORE, equipment: Equipment.CABLE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cable Woodchop'] },
  { name: 'Escaladores', nameEs: 'Mountain Climber', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Mountain Climber'] },
  { name: 'Abdominales bicicleta', nameEs: 'Bicycle Crunch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Bicycle Crunch'] },
  { name: 'Toques de tobillo', nameEs: 'Heel Touch', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Crunch'] },
  { name: 'Bicho muerto', nameEs: 'Dead Bug', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Dead Bug'] },
  { name: 'Pájaro perro', nameEs: 'Bird Dog', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Bird Dog'] },
  { name: 'L-Sit', nameEs: 'L Sit', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['L-Sit'] },

  // CALVES
  { name: 'Elevación de talones de pie en máquina', nameEs: 'Standing Calf Raise', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Standing Calf Raise'] },
  { name: 'Elevación de talones sentado en máquina', nameEs: 'Seated Calf Raise', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Seated Calf Raise'] },
  { name: 'Elevación de talones en prensa de piernas', nameEs: 'Leg Press Calf Raise', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.MACHINE, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Leg Press Calf Raise'] },
  { name: 'Elevación de talones burro', nameEs: 'Donkey Calf Raise', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Donkey Calf Raise'] },
  { name: 'Elevación de talones unilateral con mancuerna', nameEs: 'Single Leg Calf Raise', muscleGroup: MuscleGroup.CALVES, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Single Leg Calf Raise'] },

  // FOREARMS
  { name: 'Curl de antebrazo con barra en pronación', nameEs: 'Wrist Curl', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Wrist Curl'] },
  { name: 'Curl de antebrazo con barra en supinación', nameEs: 'Reverse Wrist Curl', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Reverse Wrist Curl'] },
  { name: 'Rodillo de muñeca', nameEs: 'Wrist Roller', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Wrist Roller'] },
  { name: 'Sujeción de discos con dedos', nameEs: 'Plate Pinch', muscleGroup: MuscleGroup.FOREARMS, equipment: Equipment.OTHER, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Plate Pinch'] },

  // FULL_BODY
  { name: 'Cargada y envión', nameEs: 'Clean and Jerk', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Clean and Press'] },
  { name: 'Arranque', nameEs: 'Snatch', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Snatch'] },
  { name: 'Cargada de potencia', nameEs: 'Power Clean', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Clean'] },
  { name: 'Cargada desde colgado', nameEs: 'Hang Clean', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Clean'] },
  { name: 'Press de empuje', nameEs: 'Push Press', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Press'] },
  { name: 'Sentadilla con press', nameEs: 'Thruster', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Thruster'] },
  { name: 'Balanceo con kettlebell', nameEs: 'Kettlebell Swing', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.KETTLEBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Kettlebell Swing'] },
  { name: 'Lanzamiento a pared', nameEs: 'Wall Ball', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Wall Ball'] },
  { name: 'Flexión con salto', nameEs: 'Burpee', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Burpee'] },
  { name: 'Salto al cajón', nameEs: 'Box Jump', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Box Jump'] },
  { name: 'Saltar la soga', nameEs: 'Jump Rope', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Jump Rope'] },
  { name: 'Empuje de trineo', nameEs: 'Sled Push', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.OTHER, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Sled Push'] },
  { name: 'Arranque con mancuerna', nameEs: 'Dumbbell Snatch', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Snatch'] },

  // EXTRA VARIATIONS
  { name: 'Press de suelo con barra', nameEs: 'Floor Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Floor Press'] },
  { name: 'Press Spoto', nameEs: 'Spoto Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bench Press'] },
  { name: 'Sentadilla Anderson', nameEs: 'Anderson Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Box Squat'] },
  { name: 'Sentadilla Zercher', nameEs: 'Zercher Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BARBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Front Squat'] },
  { name: 'Peso muerto con barra hexagonal', nameEs: 'Trap Bar Deadlift', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Peso muerto sumo', nameEs: 'Sumo Deadlift', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deadlift'] },
  { name: 'Peso muerto en déficit', nameEs: 'Deficit Deadlift', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.HINGE, imageUrl: EXERCISE_IMAGE_URLS['Deficit Deadlift'] },
  { name: 'Remo Kroc', nameEs: 'Kroc Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.DUMBBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Dumbbell Row'] },
  { name: 'Remo Pendlay', nameEs: 'Pendlay Row', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Barbell Row'] },
  { name: 'Dominadas comando', nameEs: 'Commando Pull Up', muscleGroup: MuscleGroup.BACK, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Pull-up'] },
  { name: 'Flexiones comando', nameEs: 'Commando Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Flexiones con palmada', nameEs: 'Clap Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Flexiones de pino', nameEs: 'Handstand Push Up', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Press Bradford', nameEs: 'Bradford Press', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Bradford Press'] },
  { name: 'Elevaciones en Y', nameEs: 'Y Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Y Raise'] },
  { name: 'Elevaciones Lu', nameEs: 'Lu Raise', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Lateral Raise'] },
  { name: 'Press Tate', nameEs: 'Tate Press', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['French Press'] },
  { name: 'Press JM', nameEs: 'JM Press', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.BARBELL, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['JM Press'] },
  { name: 'Flexión escapular', nameEs: 'Scapular Push Up', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.BODYWEIGHT, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Push Up'] },
  { name: 'Zancada cruzada hacia atrás', nameEs: 'Curtsy Lunge', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Lunges'] },
  { name: 'Sentadilla cosaca', nameEs: 'Cossack Squat', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.BODYWEIGHT, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Sumo Squat'] },
  { name: 'Clamshell con banda', nameEs: 'Clamshell', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.RESISTANCE_BAND, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Clamshell'] },
  { name: 'Elevación lateral de piernas', nameEs: 'Side Lying Leg Raise', muscleGroup: MuscleGroup.GLUTES, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Side Lying Leg Raise'] },
  { name: 'Escalador cruzado', nameEs: 'Cross Body Mountain Climber', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Mountain Climber'] },
  { name: 'Plancha con toques de hombro', nameEs: 'Plank Shoulder Tap', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Plancha Spiderman', nameEs: 'Spiderman Plank', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Plank'] },
  { name: 'Gato camello', nameEs: 'Cat Camel', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Cat Camel'] },
  { name: 'Curl Jefferson', nameEs: 'Jefferson Curl', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Jefferson Curl'] },
  { name: 'Limpiaparabrisas', nameEs: 'Windshield Wiper', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Windshield Wiper'] },
  { name: 'Remo alto para deltoides posterior en polea', nameEs: 'High Cable Rear Delt Row', muscleGroup: MuscleGroup.SHOULDERS, equipment: Equipment.CABLE, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Face Pull'] },
  { name: 'Press de pecho unilateral en máquina', nameEs: 'Unilateral Machine Chest Press', muscleGroup: MuscleGroup.CHEST, equipment: Equipment.MACHINE, movementType: MovementType.PUSH, imageUrl: EXERCISE_IMAGE_URLS['Machine Fly'] },
  { name: 'Zancadas estáticas hacia adelante', nameEs: 'Forward Lunge', muscleGroup: MuscleGroup.LEGS, equipment: Equipment.DUMBBELL, movementType: MovementType.SQUAT, imageUrl: EXERCISE_IMAGE_URLS['Lunges'] },
  { name: 'Curl de bíceps en multipower arrastrado', nameEs: 'Smith Machine Drag Curl', muscleGroup: MuscleGroup.BICEPS, equipment: Equipment.BARBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Drag Curl'] },
  { name: 'Extensión de tríceps tumbado en banco inclinado', nameEs: 'Incline Bench Triceps Extension', muscleGroup: MuscleGroup.TRICEPS, equipment: Equipment.DUMBBELL, movementType: MovementType.ISOLATION, imageUrl: EXERCISE_IMAGE_URLS['Overhead Triceps Extension'] },
  { name: 'Tirón alto con barra', nameEs: 'High Pull', muscleGroup: MuscleGroup.FULL_BODY, equipment: Equipment.BARBELL, movementType: MovementType.PULL, imageUrl: EXERCISE_IMAGE_URLS['Upright Row'] },
  { name: 'Paseo del oso', nameEs: 'Bear Crawl', muscleGroup: MuscleGroup.CORE, equipment: Equipment.BODYWEIGHT, movementType: MovementType.CARRY, imageUrl: EXERCISE_IMAGE_URLS['Bear Crawl'] },
];

export async function seedExercises(prismaClient: any) {
  console.log('Seeding exercises...');

  const allExercises = await prismaClient.exercise.findMany({
    where: { isGlobal: true },
    select: { id: true, name: true },
    orderBy: { id: 'asc' },
  });

  const nameMap = new Map<string, string>();
  let totalRemoved = 0;

  for (const ex of allExercises) {
    if (nameMap.has(ex.name)) {
      const keepId = nameMap.get(ex.name)!;
      const updatedSets = await prismaClient.set.updateMany({
        where: { exerciseId: ex.id },
        data: { exerciseId: keepId },
      });
      if (updatedSets.count > 0) {
        console.log(`  Reassigned ${updatedSets.count} sets from "${ex.name}" duplicate to original`);
      }
      await prismaClient.exercise.delete({ where: { id: ex.id } });
      totalRemoved++;
      console.log(`  Removed duplicate: "${ex.name}" (id: ${ex.id})`);
    } else {
      nameMap.set(ex.name, ex.id);
    }
  }

  if (totalRemoved > 0) {
    console.log(`✅ Removed ${totalRemoved} duplicate exercises`);
  } else {
    console.log('✅ No duplicate exercises found');
  }

  const existingNames = new Set(allExercises.map(e => e.name));
  const newExercises = exercises.filter(e => !existingNames.has(e.name));

  if (newExercises.length > 0) {
    await prismaClient.exercise.createMany({
      data: newExercises.map(e => ({
        ...e,
        isGlobal: true,
        secondaryMuscles: [],
        userId: null,
      })),
      skipDuplicates: true,
    });
    console.log(`✅ Seeded ${newExercises.length} new exercises (${existingNames.size} already existed)`);
  } else {
    console.log(`✅ All ${exercises.length} exercises already exist, no new exercises seeded`);
  }

  console.log('Updating exercise images...');
  let updatedImages = 0;
  for (const ex of exercises) {
    if (ex.imageUrl) {
      const result = await prismaClient.exercise.updateMany({
        where: { name: ex.name, isGlobal: true },
        data: { imageUrl: ex.imageUrl },
      });
      if (result.count > 0) {
        updatedImages += result.count;
      }
    }
  }
  console.log(`✅ Updated ${updatedImages} exercise images`);
}