import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const EXERCISE_IMAGE_URLS: Record<string, string> = {
  'Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg',
  'Incline Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg',
  'Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Flyes/0.jpg',
  'Cable Crossover': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg',
  'Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg',
  'Incline Dumbbell Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg',
  'Machine Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg',
  'Svend Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Svend_Press/0.jpg',
  'Floor Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Press/0.jpg',
  'Push Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clock_Push-Up/0.jpg',
  'Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Axle_Deadlift/0.jpg',
  'Barbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg',
  'Dumbbell Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg',
  'Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg',
  'Lat Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg',
  'Cable Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elevated_Cable_Rows/0.jpg',
  'Face Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg',
  'T-Bar Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_T-Bar_Row/0.jpg',
  'Deficit Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Deficit_Deadlift/0.jpg',
  'Rack Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rack_Pull_with_Bands/0.jpg',
  'High Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Row/0.jpg',
  'Straight Arm Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Straight_Arm_Pulldown/0.jpg',
  'Wide Grip Pulldown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Pulldown/0.jpg',
  'Chin-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg',
  'Superman': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Superman/0.jpg',
  'Back Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Back_Extensions/0.jpg',
  'Front Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Barbell_Squat/0.jpg',
  'Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg',
  'Leg Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg',
  'Leg Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Curls/0.jpg',
  'Hip Thrust': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg',
  'Romanian Deadlift': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg',
  'Lunges': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg',
  'Incline Leg Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Leg_Press/0.jpg',
  'Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg',
  'Hack Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg',
  'Goblet Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg',
  'Box Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Squat/0.jpg',
  'Sissy Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sissy_Squat/0.jpg',
  'Leg Press Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press_Calf_Raise/0.jpg',
  'Walking Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking_Lunges/0.jpg',
  'Reverse Lunge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Lunges/0.jpg',
  'Pistol Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pistol_Squat/0.jpg',
  'Jefferson Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jefferson_Squats/0.jpg',
  'Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lateral_Raise/0.jpg',
  'Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Raise/0.jpg',
  'Arnold Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg',
  'Rear Delt Fly': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rear_Delt_Fly/0.jpg',
  'Cable Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Lateral_Raise/0.jpg',
  'Cable Front Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Front_Raise/0.jpg',
  'Machine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Lateral_Raise/0.jpg',
  'Push Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push_Press/0.jpg',
  'Z Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Z_Press/0.jpg',
  'Bradford Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bradford_Press/0.jpg',
  'Y Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Y_Raise/0.jpg',
  'W Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/W_Raise/0.jpg',
  'Around The World': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Around_The_Worlds/0.jpg',
  'Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Row/0.jpg',
  'Cable Upright Row': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Upright_Row/0.jpg',
  'Landmine Lateral Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_Lateral_Raise/0.jpg',
  'Trap Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trap_Raise/0.jpg',
  'Barbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg',
  'EZ Bar Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg',
  'Alternating Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternating_Dumbbell_Curl/0.jpg',
  'Hammer Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curl/0.jpg',
  'Concentration Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curl/0.jpg',
  'Cable Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Curl/0.jpg',
  'Incline Dumbbell Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg',
  'Preacher Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg',
  'Spider Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spider_Curl/0.jpg',
  'Drag Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Drag_Curl/0.jpg',
  'Waiter Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Waiter_Curl/0.jpg',
  'Cross Body Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross_Body_Curl/0.jpg',
  'French Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/French_Press/0.jpg',
  'Triceps Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg',
  'Close Grip Bench Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Bench_Press/0.jpg',
  'Triceps Dips': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Dips/0.jpg',
  'Triceps Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Kickback/0.jpg',
  'Overhead Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Triceps_Extension/0.jpg',
  'JM Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/JM_Press/0.jpg',
  'Cable Overhead Triceps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Overhead_Triceps/0.jpg',
  'Reverse Grip Pushdown': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Pushdown/0.jpg',
  'Lying Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Extension/0.jpg',
  'Single Arm Triceps Extension': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Triceps_Extension/0.jpg',
  'Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg',
  'Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch/0.jpg',
  'Cable Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg',
  'Ab Wheel Rollout': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Wheel_Rollout/0.jpg',
  'Hanging Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg',
  'Russian Twist': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg',
  'Dead Bug': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg',
  'Bird Dog': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bird_Dog/0.jpg',
  'Side Plank': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Plank/0.jpg',
  'V-Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Up/0.jpg',
  'Toe to Bar': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Toe_to_Bar/0.jpg',
  'Windshield Wiper': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Windshield_Wiper/0.jpg',
  'L-Sit': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/L-Sit/0.jpg',
  'Dragon Flag': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dragon_Flag/0.jpg',
  'Cable Woodchop': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Woodchop/0.jpg',
  'Pallof Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pallof_Press/0.jpg',
  'Mountain Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climber/0.jpg',
  'Hollow Body Hold': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hollow_Body_Hold/0.jpg',
  'Bicycle Crunch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bicycle_Crunch/0.jpg',
  'Leg Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Raise/0.jpg',
  'Glute Bridge': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Bridge/0.jpg',
  'Cable Kickback': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Kickback/0.jpg',
  'Bulgarian Split Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bulgarian_Split_Squat/0.jpg',
  'Step Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step-Up/0.jpg',
  'Sumo Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Squat/0.jpg',
  'Seated Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg',
  'Standing Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raise/0.jpg',
  'Donkey Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raise/0.jpg',
  'Single Leg Calf Raise': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Calf_Raise/0.jpg',
  'Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wrist_Curl/0.jpg',
  'Reverse Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Curl/0.jpg',
  'Reverse Wrist Curl': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Wrist_Curl/0.jpg',
  'Farmer Carry': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Farmer_Carry/0.jpg',
  'Plate Pinch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plate_Pinch/0.jpg',
  'Towel Pull-up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Towel_Pull-Up/0.jpg',
  'Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Running/0.jpg',
  'Walking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Walking/0.jpg',
  'Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cycling/0.jpg',
  'Swimming': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming/0.jpg',
  'Rowing Machine': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rowing_Machine/0.jpg',
  'Elliptical': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Elliptical/0.jpg',
  'Stair Climber': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stair_Climber/0.jpg',
  'Jump Rope': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jump_Rope/0.jpg',
  'Sprint': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sprint/0.jpg',
  'Hiking': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hiking/0.jpg',
  'Treadmill Run': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Run/0.jpg',
  'Treadmill Walk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Treadmill_Walk/0.jpg',
  'Stationary Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stationary_Bike/0.jpg',
  'Spin Bike': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Spin_Bike/0.jpg',
  'Indoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Indoor_Cycling/0.jpg',
  'Outdoor Cycling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Outdoor_Cycling/0.jpg',
  'Trail Running': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trail_Running/0.jpg',
  'HIIT': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/HIIT/0.jpg',
  'Tabata': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tabata/0.jpg',
  'Circuit Training': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Circuit_Training/0.jpg',
  'Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Aerobics/0.jpg',
  'Dance': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dance/0.jpg',
  'Yoga': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Yoga/0.jpg',
  'Pilates': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pilates/0.jpg',
  'Stretching': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stretching/0.jpg',
  'Mobility': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mobility/0.jpg',
  'Foam Rolling': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Foam_Rolling/0.jpg',
  'Swimming Laps': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Swimming_Laps/0.jpg',
  'Open Water Swim': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Open_Water_Swim/0.jpg',
  'Water Aerobics': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Water_Aerobics/0.jpg',
  'Clean and Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_and_Press/0.jpg',
  'Thruster': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thruster/0.jpg',
  'Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Swing/0.jpg',
  'Burpee': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Burpee/0.jpg',
  'Turkish Get Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Turkish_Get_Up/0.jpg',
  'Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch/0.jpg',
  'Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean/0.jpg',
  'Jerk': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Jerk/0.jpg',
  'Muscle Up': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Muscle_Up/0.jpg',
  'Box Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Box_Jump/0.jpg',
  'Broad Jump': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Broad_Jump/0.jpg',
  'Medicine Ball Slam': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Medicine_Ball_Slam/0.jpg',
  'Battle Ropes': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Battle_Ropes/0.jpg',
  'Sled Push': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Push/0.jpg',
  'Sled Pull': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sled_Pull/0.jpg',
  'Wall Ball': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wall_Ball/0.jpg',
  'Kettlebell Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Clean/0.jpg',
  'Kettlebell Snatch': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Snatch/0.jpg',
  'Kettlebell Press': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Press/0.jpg',
  'Single Arm Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Arm_Swing/0.jpg',
  'Goblet Clean': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Clean/0.jpg',
  'Double Kettlebell Swing': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Double_Kettlebell_Swing/0.jpg',
  'Kettlebell Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Squat/0.jpg',
  'Overhead Squat': 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Overhead_Squat/0.jpg',
};

async function main() {
  console.log('Updating exercise images...');
  let updated = 0;
  for (const [name, url] of Object.entries(EXERCISE_IMAGE_URLS)) {
    const result = await prisma.exercise.updateMany({
      where: { name, isGlobal: true },
      data: { imageUrl: url },
    });
    if (result.count > 0) {
      updated += result.count;
      console.log(`  Updated ${name} -> ${url}`);
    } else {
      console.log(`  Not found: ${name}`);
    }
  }
  console.log(`Done. Updated ${updated} exercises.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
